config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create]
  delete 'sign_out' => 'sessions#destroy'
  root 'pages#home'

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, :email, presence: true

  has_secure_password

  # user = User.find(1)
  # user.record_sign_in
  def record_sign_in
    update!(last_signed_in_at: Time.now)
    # send a text message?
    # update their points?
    # notify the NSA?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :is_admin?

  def is_admin?
    current_user && current_user.admin?
  end

  def current_user
    if session.key?(:user_id)
      User.find(session[:user_id])
    else
      nil
    end
  end

  private

  def sign_in_user(user)
    user.record_sign_in
    session[:user_id] = user.id
  end

  def ensure_admin
    return true if is_admin?
    redirect_to root_path, notice: 'No way -- not an admin!'
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(email: session_params[:email])
    if user && user.authenticate(session_params[:password])
      sign_in_user(user)
      redirect_to root_path, notice: 'Hi, friend!'
    else
      redirect_to root_path, notice: 'No way!'
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path, notice: 'Bye!'
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :lookup_user, only: [:edit, :update, :destroy]
  before_action :ensure_admin, only: [:index, :destroy]
  before_action :ensure_current_user, only: [:edit, :update]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.create!(user_params)
    sign_in_user(@user)
    redirect_after_success
  end

  def update
    @user.update(user_params)
    redirect_after_success
  end

  def destroy
    @user.destroy
    redirect_after_success('Poof! Gone!')
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def lookup_user
    @user = User.find(params[:id])
  end

  def ensure_current_user
    if current_user == @user
      true
    else
      redirect_to root_path, error: 'Not allowed'
    end
  end

  def redirect_after_success(notice = nil)
    redirect_to(root_path, {notice: notice})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Authentic</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class='container'>

<%= link_to 'Sign out', sign_out_path, method: :delete %>
<pre><%= current_user.inspect %></pre>

<pre><%= flash.inspect %></pre>
<%= yield %>
</div>
</body>
</html>

app/views/pages/home.html.erb
<h1>Hi!</h1>

<%= render 'sessions/form' %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

  name<br>
  <%= f.text_field :name %>

  <br><br>
  email<br>
  <%= f.email_field(:email, {}) %>

  <br><br>
  password<br>
  <%= f.password_field :password %>

  <button type="submit">Save</button>


<% end %>

app/views/users/edit.html.erb
<div class='page-header'>
  <h2>Edit your profile</h2>
</div>

<%= render 'form', user: @user %>

app/views/users/index.html.erb
<% @users.each do |user| %>

  <pre><%= user.inspect %></pre>

  <%= link_to 'Edit', edit_user_path(user) %>
  <%= link_to 'Delete',
              user_path(user),
              method: :delete, data: { confirm: 'Really?' } %>

<% end %>

app/views/users/new.html.erb
<div class='page-header'>
  <h2>Sign up</h2>

</div>

<%= render 'form', user: @user %>